# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5f27538f72840e12eb83dafb05db8c0c470c1d9d5b95987c6d8ed9658227a041b69c8eeda35addedb4cb9999941bb1f57329e246a8ea8991f20c126916cf5475

test:
  secret_key_base: cb11f74006043f794967a0332d2c33484ab909a17e7e22a67e2f8c23c5f61ebe58a218c882c83e080159f50a84129d9cf5930d95e5c41096bb43c921ddff87e0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
